---
- hosts: localhost
  tasks:
    - name: install packages
      become: true
      become_user: root
      dnf:
        state: present
        name:
          - cockpit-ovirt-dashboard
          - vdsm-gluster
          - ovirt-host
    - name: Add ovirtglusteradmin
      ansible.builtin.user:
        name: ovirtgluster
        comment: oVirt Gluster
        group: root
    - name: oVirtgluster Key
      ansible.posix.authorized_key:
        user: ovirtgluster
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDndP5rLa8Z9sPpVRCz+l19MKIWRdDyK8k+48hy+ai4LkALEOZRd1y8GpbZfRFu6ZxdH+0oe1z/UyE0AHtETInd/n7A2X8jNNDqnpNyupYuxNzW7SaFzMFwVHmYqsfEmLq73Y2zj7QxleyHE9Z7OV3b4mr7U0HU7TItOxnDeKwyOQDqoErtcYOj/7OaC4gcV2CFJGB8EfMiJP1Qal3ReAuqdxfXfN+EV92xYPz1jBxNJfZ2/xAVAQdoJLgei8wN4EjJbW+0mxRaVwXwe2ro48Tx5lGFidFCqyssSJj/A0biSbBZhl4t2LAU+mmvFu6zuy28X8L4yJYnwg1Z4+PWvfhG/5SSzYOc87UI2UfF9WiWnI/VwBUSdMClAzH8seCKY41XrryIqThpTBt3emrXg82XCV4+O6ZT5a18M7mB59t3DXH+kJNSZgkEZP8ypKDocyjwguZ0uSkbIegA4DGCEQKXfaR9jTsnAnUHfbVHYGqri+cqs8HZo6Gshy+x5Z6cLyU= ovirtgluster@north36.maas"
    - name: Enable oVirtGluster User passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.s/boces-init-users
        regexp: '^ovirtgluster'
        line: ovirtgluster ALL=(ALL) NOPASSWD:ALL
