---
- hosts: localhost
  tasks:
    - name: install packages
      become: true
      become_user: root
      dnf:
        state: present
        name:
          - cockpit-ovirt-dashboard
          - vdsm-gluster
          - ovirt-host
          - gluster-ansible-roles
    - name: Add ovirtglusteradmin
      ansible.builtin.user:
        name: ovirtgluster
        comment: oVirt Gluster
        group: root
    - name: Enable Root Login
      ansible.builtin.lineinfile:
        path: /root/.ssh/authorized_keys
        state: absent
        regexp: '^no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo '
    - name: Root Key
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCf7blqhy4V4ftVyFUMIulWNmJzb88HWdsb/msGJQ8ZGc+HWVetpZH0hJouxOuiO6WMVy2RSoCxMgQGzVAlLiTsK5TChmT4CMQhW2JC51sIN7fCfA+bOW1JzRo0xbDWlIuauQ5xvlLXZanRVqfcD7R/Ebp3cduxoNq3Z6wLnDDa64OyPIIZYvC8q+edhJl4CTJBmGr6WoheS0e0Mv/FosdmcobW+F5eDhJ6uNu2fipZ6inGTnRcJDa5ubRf18pluyBQdbZnwwq+iCqNgzuBm4DmcESNkGX2iAKIWjecXNIoRXvJoeHH1tdldP7k08eQd3u0+Oi0gJ3iml7K8+aivqutuHoYHdWzZaeBeu623z1zgww0Zh83UgW3ChY6FrUPeaTJRAYsOMcvBoxUCNHANuF+WCf9yuxF4nkWopbnSY4fqMg1iVGSSTafVk9rAIR3FsmHbKJ5Dh4Eark3FImuR1OxrPXSBOLl+9iPyzp4bLzyQBeobSphauckE2Cqke/MMX0= root@north36.maas"
    - name: Enable oVirtGluster User passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/boces-init-users
        regexp: '^ovirtgluster'
        line: ovirtgluster ALL=(ALL) NOPASSWD:ALL
